### ISSUE TITLE
Update README with Python minimum version

### ISSUE THREAD

**Issue by pablodiogenes** [drewmullen/ansible-vault-namespaces#6]
Spun my wheels on this for some time before hunting down an issue that casually mentioned that some things only work for Python 3.7... Was running into this with 3.5 on an `ansible-playbook` execution:

```
Traceback (most recent call last):
  File "/home/devadmin/.ansible/tmp/ansible-tmp-1563913106.429221-106783159154991/AnsiballZ_hashivault_azure_auth_role.py", line 114, in <module>
    _ansiballz_main()
  File "/home/devadmin/.ansible/tmp/ansible-tmp-1563913106.429221-106783159154991/AnsiballZ_hashivault_azure_auth_role.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/devadmin/.ansible/tmp/ansible-tmp-1563913106.429221-106783159154991/AnsiballZ_hashivault_azure_auth_role.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/home/devadmin/git/ansible-vault-namespaces/venv/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/devadmin/git/ansible-vault-namespaces/venv/lib/python3.5/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/tmp/ansible_hashivault_azure_auth_role_payload_exaje60e/__main__.py", line 221, in <module>
  File "/tmp/ansible_hashivault_azure_auth_role_payload_exaje60e/__main__.py", line 138, in main
  File "/tmp/ansible_hashivault_azure_auth_role_payload_exaje60e/ansible_hashivault_azure_auth_role_payload.zip/ansible/module_utils/hashivault.py", line 32, in hashivault_init
  File "/tmp/ansible_hashivault_azure_auth_role_payload_exaje60e/ansible_hashivault_azure_auth_role_payload.zip/ansible/module_utils/basic.py", line 682, in __init__
  File "/tmp/ansible_hashivault_azure_auth_role_payload_exaje60e/ansible_hashivault_azure_auth_role_payload.zip/ansible/module_utils/basic.py", line 1555, in _check_required_if
  File "/tmp/ansible_hashivault_azure_auth_role_payload_exaje60e/ansible_hashivault_azure_auth_role_payload.zip/ansible/module_utils/common/validation.py", line 250, in check_required_if
ValueError: too many values to unpack (expected 3)
```

It might be a good idea to call out the prereqs in the readme.

**Comment by drewmullen** [comment]
good suggestion! i actually [ran into this](https://github.com/TerryHowe/ansible-modules-hashivault/pull/133/commits/0fc78684302138b913b52725c1122efd034a70dc) while developing some of these modules in terryhowe/ansible-modules-hashitvault
